name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MULE_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      MULE_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <pluginGroups>
              <pluginGroup>org.mule.tools</pluginGroup>
              <pluginGroup>org.mule.tools.maven</pluginGroup>
            </pluginGroups>
            <servers>
              <server>
                <id>Repository</id>
                <username>${MULE_CLIENT_ID}</username>
                <password>${MULE_CLIENT_SECRET}</password>
              </server>
              <server>
                <id>anypoint-exchange</id>
                <username>${MULE_CLIENT_ID}</username>
                <password>${MULE_CLIENT_SECRET}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build Mule Application
        run: mvn clean package -DskipMunitTests

      - name: Publish to Exchange
        run: mvn org.mule.tools.maven:exchange-mule-maven-plugin:0.0.23:exchange-deploy -DskipMunitTests

      - name: Deploy to CloudHub 2.0
        run: mvn deploy -DskipMunitTests -DmuleDeploy