name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MULE_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      MULE_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 8

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cp .maven/settings.xml ~/.m2/settings.xml

      - name: Publish to Exchange
        run: |
          mvn deploy -DskipMunitTests

      - name: Deploy to CloudHub 2.0
        run: |
          mvn deploy -DskipMunitTests -DmuleDeploy