name: Build and Deploy to CloudHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Stamp artifact with commit hash
        run: |
          artifact=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          renamedArtifact=$(echo "$artifact" | sed "s/.jar/-$commitHash.jar/")
          mv "$artifact" "$renamedArtifact"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mule-artifact
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: mule-artifact
          path: .

      - name: Deploy to CloudHub
        run: |
          artifact=$(ls *.jar | head -1)
          mvn deploy -DskipTests -DmuleDeploy \
            -Dmule.artifact="$artifact" \
            -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
            -Denv="${{ secrets.DEPLOY_ENV }}" \
            -Danypoint.platform.client_id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
            -Danypoint.platform.client_secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"